language: java

services:
 - docker
 
before_install:
  - docker run -d -p 127.0.0.1:80:4567 xaniNiehaus/green /bin/sh -c "cd /root/green; bundle exec foreman start;"
  - docker ps -a
  - docker run xaniNiehaus/green /bin/sh -c "cd /root/green; bundle exec rake test"

script:
 - ant;
 - ant test;
