sudo: required

language: java

services:
  - docker

before_install:
  - docker ps -aq -f status=exited
  - docker build -t greenimage .

script:
  - docker run greenimage /bin/sh -c "ant; ant test;"
