sudo: required

language: java

services:
    - docker

before_install:
    - docker build -t hen3kr8/green/Dockerfile .
#    - docker run -d -p 127.0.0.1:80:4567
    - docker ps -a
    - docker run hen3kr8/green/Dockerfile

script:
    - ant;
    - ant test;
