sudo: required

language: java

services:
 - docker

before_install:
  - docker ps -aq f status=exited
  - docker build -t 18966330/dock .

script:
 - docker run 18966330/dock /bin/sh -c "ant; ant test"
