sudo: required

language: java

services:
    - docker

before_install:
    - docker build -t hen3kr8/green .
    - docker run -d -p 127.0.0.1:80:4567 hen3kr8/green /bin/sh-c
    - docker ps -a
    - docker run hen3kr8/green

script:
    - ant;
    - ant test;
