sudo: required
dist: trusty

services: docker

before_install:
  - docker build -t carlad/sinatra .
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd carla/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd carla/sinatra; bundle exec rake test"

language: java

script:
 - ant;
 - ant test;
