required: sudo

services:
 - docker

language: java

#Builds Docker Image directly from GitHub repository
before_install:
- docker build -t green

#Runs the test from the docker shell
script:
 - docker run green /bin/sh -c "ant; ant test"
