sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t 20289472/green .
  - docker run -d -p 127.0.0.1:80:4567 20289472/green /bin/sh -c "cd /root/green; bundle exec foreman start;"
  - docker ps -a
  - docker run 20289472/green /bin/sh -c "cd /root/green; bundle exec rake test"

script:
 - ant;
 - ant test;
 


