sudo: required

language: java

services:
  - docker

before_install:
  - docker ps -aq -f status=exited
  - docker build -t friendlygreen .

script:
 - docker run friendlygreen /bin/sh -c "ant; ant test"
 - docker ps -a
