language: java

script:
 - ant;
 - ant test;

sudo: required

services:
 - docker

before_install:
 - docker build ./ -t buildc
 - docker run -d -p 127.0.0.1:4567 buildc /bin/sh -c "cd /green/; ant; ant test;"

