sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t sat3 .
  #- docker run -d -p 127.0.0.1:80:4567 sat3 /bin/sh -c "cd /root/green; ant; ant test;"
  #- docker ps -a

script:
 # - ant;
 # - ant test;
 # - docker run sat3 /bin/sh -c "cd /root/green; ant;"
  - docker run sat3 /bin/sh -c "ant; ant test;"

# Bonus Deliverable
after_failure:
  - docker run sat3 /bin/sh -c "pwd;ls;"
