sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t 20039867/green .
  - docker run 20039867/green bin/sh -c "ant; ant test"

script:
  - docker run 20039867/green bin/sh -c "ant; ant test"
